// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG_sWbyJGUvf5veIhDVbctWTh8DQWbwFQ',
    appId: '1:1033490564901:web:fd65a439809489e238bccc',
    messagingSenderId: '1033490564901',
    projectId: 'mnprojectdelivsym',
    authDomain: 'mnprojectdelivsym.firebaseapp.com',
    storageBucket: 'mnprojectdelivsym.firebasestorage.app',
    measurementId: 'G-EXQX2MV0Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB_sgzruf-3MzefRKUzy9rTCrr8vJcF3w',
    appId: '1:1033490564901:android:1ba9e6a86b7a9f6638bccc',
    messagingSenderId: '1033490564901',
    projectId: 'mnprojectdelivsym',
    storageBucket: 'mnprojectdelivsym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK65d6_54sPfdc673SNWHnozsCa90bHZM',
    appId: '1:1033490564901:ios:34a331ae3fdaa7a338bccc',
    messagingSenderId: '1033490564901',
    projectId: 'mnprojectdelivsym',
    storageBucket: 'mnprojectdelivsym.firebasestorage.app',
    iosBundleId: 'com.example.mnProj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK65d6_54sPfdc673SNWHnozsCa90bHZM',
    appId: '1:1033490564901:ios:34a331ae3fdaa7a338bccc',
    messagingSenderId: '1033490564901',
    projectId: 'mnprojectdelivsym',
    storageBucket: 'mnprojectdelivsym.firebasestorage.app',
    iosBundleId: 'com.example.mnProj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG_sWbyJGUvf5veIhDVbctWTh8DQWbwFQ',
    appId: '1:1033490564901:web:f0eccf3b8800a72638bccc',
    messagingSenderId: '1033490564901',
    projectId: 'mnprojectdelivsym',
    authDomain: 'mnprojectdelivsym.firebaseapp.com',
    storageBucket: 'mnprojectdelivsym.firebasestorage.app',
    measurementId: 'G-3YXEWJ62DR',
  );
}
